---
sudo: false
language: ruby
cache: bundler
dist: bionic
rvm:
  - 2.6
services:
  - postgresql
  - mysql
before_script:
  - createdb -U postgres constant_table_saver_test
  - mysqladmin -u root create constant_table_saver_test
script: ./test_all.rb
